Repository Sage-Bionetworks/sage-monorepo, pull requests merged in 2022-07, with the labels that each got.

#358 Update home page
  libs/challenge-registry/assets/src/assets/images/aws.png
  libs/challenge-registry/assets/src/assets/images/cagi.png
  libs/challenge-registry/assets/src/assets/images/miccai.png
  libs/challenge-registry/assets/src/assets/images/openapi.png
  libs/challenge-registry/assets/src/assets/images/precisionfda.png
  libs/challenge-registry/assets/src/assets/images/sage.png
  libs/challenge-registry/home/src/lib/challenge-host-list/challenge-host-list.component.html
  libs/challenge-registry/home/src/lib/challenge-host-list/challenge-host-list.component.scss
  libs/challenge-registry/home/src/lib/challenge-registration/challenge-registration.component.html
  libs/challenge-registry/home/src/lib/challenge-registration/challenge-registration.component.scss
  libs/challenge-registry/home/src/lib/challenge-registration/challenge-registration.module.ts
  libs/challenge-registry/home/src/lib/challenge-search/challenge-search.component.html
  libs/challenge-registry/home/src/lib/challenge-search/challenge-search.component.scss
  libs/challenge-registry/home/src/lib/featured-challenge-list/_featured-challenge-list-theme.scss
  libs/challenge-registry/home/src/lib/featured-challenge-list/featured-challenge-list.component.html
  libs/challenge-registry/home/src/lib/featured-challenge-list/featured-challenge-list.component.scss
  libs/challenge-registry/home/src/lib/home.component.html
  libs/challenge-registry/home/src/lib/sponsor-list/sponsor-list.component.html
  libs/challenge-registry/home/src/lib/sponsor-list/sponsor-list.component.scss
  libs/challenge-registry/home/src/lib/statistics-viewer/statistics-viewer.component.html
  libs/challenge-registry/home/src/lib/statistics-viewer/statistics-viewer.component.scss
  libs/challenge-registry/home/src/lib/topics-viewer/topics-viewer.component.html
  libs/challenge-registry/home/src/lib/topics-viewer/topics-viewer.component.scss
  libs/challenge-registry/ui/src/_lib-theme.scss
  libs/challenge-registry/ui/src/lib/_palette.scss
  libs/challenge-registry/ui/src/lib/navbar/_navbar-theme.scss
Labels: frontend

#401 Remove vscode extension version from devcontainer.json
  .devcontainer/devcontainer.json
  .vscode/settings.json
Labels: dev/devcontainer, dev/env

#404 Rely on local app config for the api gateway
  apps/challenge-api-gateway/pom.xml
  apps/challenge-api-gateway/project.json
  apps/challenge-api-gateway/src/main/resources/_bootstrap.yml
  apps/challenge-api-gateway/src/main/resources/application.yml
Labels: java/spring
